spring.application.name=concursoexpress

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/concursoExpressDB
spring.datasource.username=postgres
spring.datasource.password=Uisrael.

spring.jpa.show-sql=true
